name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HG }}
        run: git remote add space https://kl08:$HF@huggingface.co/spaces/kl08/hg-demo-w-github
      - name: Push to hub
        env:
          HF: ${{ secrets.HG }}
        run: git push --force https://kl08:$HF@huggingface.co/spaces/kl08/hg-demo-w-github main
